services:
  grpc-envoy:
    image: envoyproxy/envoy:v1.34-latest
    ports:
      - "9901:9901"
      - "8080:8080"
    volumes:
      - "./envoy.yaml:/etc/envoy/envoy.yaml"
  node-red:
    image: vestra/node-red
    build:
      context: .
      dockerfile: nodes/Dockerfile
    ports:
      - "1880:1880"
    volumes:
      - "${NODE_RED_DATA_DIR}:/data"
  backend:
    image: vestra/orchestrator
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "50051:50051"
    volumes:
      - "${NODE_RED_DATA_DIR}:/node-red"
    environment:
      NODE_RED_DIR: "/node-red"